	/* sccs id   @(#)ex_vars.h makeoptions	1.8 (gritter) 7/1/02 */
#define AUTOINDENT      0
#define AUTOPRINT       1
#define AUTOWRITE       2
#define BEAUTIFY        3
#define DIRECTORY       4
#define EDCOMPATIBLE    5
#define ERRORBELLS      6
#define EXRC            7
#define FLASH           8
#define HARDTABS        9
#define IGNORECASE      10
#define LISP            11
#define LIST            12
#define MAGIC           13
#define MESG            14
#define MODELINES       15
#define NUMBER          16
#define OPEN            17
#define OPTIMIZE        18
#define PARAGRAPHS      19
#define PROMPT          20
#define READONLY        21
#define REDRAW          22
#define REMAP           23
#define REPORT          24
#define SCROLL          25
#define SECTIONS        26
#define SHELL           27
#define SHIFTWIDTH      28
#define SHOWMATCH       29
#define SHOWMODE        30
#define SLOWOPEN        31
#define SOURCEANY       32
#define TABSTOP         33
#define TAGLENGTH       34
#define TAGS            35
#define TERM            36
#define TERSE           37
#define TIMEOUT         38
#define TTYTYPE         39
#define WARN            40
#define WINDOW          41
#define WRAPSCAN        42
#define WRAPMARGIN      43
#define WRITEANY        44

#define	NOPTS	45
